version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 8883:8883
      - 9002:9001
    volumes:
      - /home/debian/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - data:/mosquitto/data
    networks:
      - mosquitto
volumes:
  data:
networks:
  mosquitto:
    name: mosquitto
    driver: bridge
