services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - /home/root/docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mq_data:/mosquitto/data
    networks:
      - iotaut

volumes:
  mq_data:

networks:
  iotaut:
    driver: bridge