services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /root/docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
    networks:
      - iotaut

  z2m:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - z2m_data:/app/data
      - /root/docker/z2m.yml:/app/data/configuration.yaml
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - iotaut

  nore:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - nore_data:/data

volumes:
  mqtt_data:
  z2m_data:
  nore_data:

networks:
  iotaut:
    driver: bridge